title: 宇浩输入法
description: ·繁简通打·极致低重·全汉字输入
theme: just-the-docs

url: https://zhuyuhao.com/yuhao/

aux_links:
  官方QQ群: https://jq.qq.com/?_wv=1027&k=2OYDP4Tk

# External navigation links
nav_external_links:
  - title: 在线拆分查询系统
    url: https://zhuyuhao.com/yuhao/chaifen
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: 玫枫跟打器
    url: https://kylebing.cn/tools/typepad/
    hide_icon: false # set to true to hide the external link icon - defaults to false

markdown: kramdown